name: CI to Docker hub 
on:
  push:
    tags:        
      - '*'           # Push events to every tag not containing /
jobs:
  push_to_reg:
    name: Push to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release version number
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup docker builder
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcr.
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: build, push.
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags:  ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.version }}